/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sikelompok7;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class EditAdmin extends javax.swing.JFrame {
    DefaultTableModel model;
    String[] data;
    String header[] = new String[]{"Nama","Status","Alamat","Username","Password"};
    String[][] Data = new String [][] {{"Admin","Admin","-", "admin","admin"},
        {"Arif Rahmat I","Admin","Jl. Jeruk3","arif3","yuzu3"},{"User","User","-",
        "user","user"},{"Rimaya Dwi Atika","User","Kota Bingin","maya5","maya5"}
    };

    int row,col; 
    /**
     * Creates new form EditAdmin
     */
    public EditAdmin() {
        initComponents();
        data = new String[5];
        model = new DefaultTableModel();
        model.addColumn("Nama");
        model.addColumn("Status");
        model.addColumn("Alamat");
        model.addColumn("Username");
        model.addColumn("Password");        
         
model = new DefaultTableModel(Data, header);
        dataTabel.setModel(model);
        
        
    //Tampilan menu ke tengah    
    Dimension screenSize = 
    Toolkit.getDefaultToolkit().getScreenSize();
    Dimension frameSize = this.getSize();
    if (frameSize.height > screenSize.height) {
        frameSize.height = screenSize.height;
    }
    if (frameSize.width > screenSize.width) {
        frameSize.width = screenSize.width;
    }
    this.setLocation(
    (screenSize.width - frameSize.width) / 2, 
    (screenSize.height - frameSize.height) / 2);         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JDataAdminUser = new javax.swing.JLabel();
        isiMenu = new javax.swing.JPanel();
        Nama = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        JenisKelamin = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        txtPassword = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        tbData = new javax.swing.JScrollPane();
        dataTabel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JDataAdminUser.setFont(new java.awt.Font("Tw Cen MT", 1, 25)); // NOI18N
        JDataAdminUser.setForeground(new java.awt.Color(10, 29, 55));
        JDataAdminUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JDataAdminUser.setText("Admin Data");
        jPanel1.add(JDataAdminUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        isiMenu.setBackground(new java.awt.Color(255, 216, 204));
        isiMenu.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 189, 155)), javax.swing.BorderFactory.createTitledBorder(null, "Input Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 0, 18), new java.awt.Color(10, 29, 55)))); // NOI18N
        isiMenu.setAlignmentY(0.0F);

        Nama.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Nama.setText("Nama");

        Username.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Username.setText("Username");

        Password.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Password.setText("Password");

        JenisKelamin.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        JenisKelamin.setText("Status");

        Alamat.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Alamat.setText("Alamat");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        tbData.setAlignmentY(0.0F);

        dataTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "Status", "Alamat", "Username", "Password"
            }
        ));
        dataTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTabelMouseClicked(evt);
            }
        });
        tbData.setViewportView(dataTabel);

        javax.swing.GroupLayout isiMenuLayout = new javax.swing.GroupLayout(isiMenu);
        isiMenu.setLayout(isiMenuLayout);
        isiMenuLayout.setHorizontalGroup(
            isiMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbData)
                .addContainerGap())
            .addGroup(isiMenuLayout.createSequentialGroup()
                .addGroup(isiMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(isiMenuLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(isiMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JenisKelamin)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(isiMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(isiMenuLayout.createSequentialGroup()
                                .addGroup(isiMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(isiMenuLayout.createSequentialGroup()
                                        .addGroup(isiMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(90, 90, 90))
                                    .addGroup(isiMenuLayout.createSequentialGroup()
                                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Alamat)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(isiMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        isiMenuLayout.setVerticalGroup(
            isiMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(isiMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(isiMenuLayout.createSequentialGroup()
                        .addGroup(isiMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nama)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Alamat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(isiMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JenisKelamin)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(isiMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Username)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(isiMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(isiMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addComponent(tbData, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(isiMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 97, 600, 310));

        jButton1.setBackground(new java.awt.Color(255, 189, 155));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton1.setText("<");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bgUser.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        int jumlahBaris = dataTabel.getRowCount();
        data[0] = txtNama.getText();
        data[1] = cbStatus.getSelectedItem().toString();
        data[2] = txtAlamat.getText();
        data[3] = txtUsername.getText();
        data[4] = txtPassword.getText();

        boolean belumAda = true;
        for(int i=0;i<jumlahBaris;i++){
            if(data[0].equals(model.getValueAt(i, 0))){
                belumAda = false;
                break;
            }
        }
        if(belumAda){

            model.addRow(data);

            txtNama.setText("");
            cbStatus.setSelectedItem("");
            txtAlamat.setText("");
            txtUsername.setText("");
            txtPassword.setText("");
        }else{
            JOptionPane.showMessageDialog(null,"Data Sudah Ada!");
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        int baris = dataTabel.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) dataTabel.getModel();
        if(baris >= 0){
            model.setValueAt(txtNama.getText().trim(), baris, 0);
            model.setValueAt(cbStatus.getSelectedItem().toString().trim(), baris, 1);
            model.setValueAt(txtAlamat.getText().trim(), baris, 2);
            model.setValueAt(txtUsername.getText().trim(), baris, 3);
            model.setValueAt(txtPassword.getText().trim(), baris, 4);
    }//GEN-LAST:event_btnUbahActionPerformed
    }
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int baris = dataTabel.getSelectedRow();
        data[0] = txtNama.getText();
        data[1] = cbStatus.getSelectedItem().toString();
        data[2] = txtAlamat.getText();
        data[3] = txtUsername.getText();
        data[4] = txtPassword.getText();

        model.removeRow(baris);

        txtNama.setText("");
        cbStatus.setSelectedItem("");
        txtAlamat.setText("");
        txtUsername.setText("");
        txtPassword.setText("");

    }//GEN-LAST:event_btnHapusActionPerformed

    private void dataTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTabelMouseClicked
        int baris = dataTabel.getSelectedRow();
        //ubah 3 textfield dengan data dari tabel
        txtNama.setText(model.getValueAt(baris,0).toString());
        cbStatus.setSelectedItem(model.getValueAt(baris,1).toString());
        txtAlamat.setText(model.getValueAt(baris,2).toString());
        txtUsername.setText(model.getValueAt(baris,3).toString());
        txtPassword.setText(model.getValueAt(baris,4).toString());
    }//GEN-LAST:event_dataTabelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        berandaAdmin rg = new berandaAdmin();
        rg.setVisible(true);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setDefaultCloseOperation(berandaAdmin.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel JDataAdminUser;
    private javax.swing.JLabel JenisKelamin;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Username;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JTable dataTabel;
    private javax.swing.JPanel isiMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane tbData;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
